---
- name: install packages
  with_items: "{{ snappy_packages }}"
  pkgng:
    name: "{{ item.name }}"
  notify:
    - restart php-fpm

- name: set data dir perms
  file:
    path: /usr/local/www/snappymail/data
    mode: 0775
    group: www

- name: configure php-fpm pool
  template:
    src: www.conf.j2
    dest: /usr/local/etc/php-fpm.d/www.conf
  notify:
    - restart php-fpm

- name: enable php-fpm
  template:
    src: php_fpm.j2
    dest: /etc/rc.conf.d/php_fpm
  notify:
    - restart php-fpm
